spring:
    application:
        name: cotrip-backend
    mvc:
        servlet:
          path: /api/v1
    datasource:
        url: jdbc:postgresql://localhost:5432/cotrip
        username: username
        password: password
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      show-sql: false
      database: postgresql
logging:
    level:
      org:
        springframework=DEBUG:
server:
  port: 8081


