spring:
    application:
        name: cotrip-backend
    mvc:
        servlet:
          path: /api/v1
    datasource:
        url: jdbc:postgresql://localhost:5432/db
        username: cotrip
        password: cotrip
        driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      show-sql: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql
logging:
    level:
      org:
        springframework=DEBUG:


