name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Login to DockerHub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            push: true
            platforms: linux/amd64
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/cotrip-backend:latest
            build-args: |
              PROFILE=dev
